### ISSUE TITLE
Add ROOAAAR - French Language Pack for Flarum's third-party extensions

### ISSUE THREAD

**Issue by Hiobi** [rob006-software/flarum-translations#514] opened 2021-04-25 09:57 UTC
Hi Rob006,

Could you add my French Language Pack for Flarum's third-party extensions (84 translated), please? :smiley: 

- I created my account : https://weblate.rob006.net/user/Hiobi/
- I invited robbot006 to my repo : https://github.com/rooaaar/lang-french-extended

Let me known if everything is ok or not.
Thanks !

**Comment by rob006** [comment] 2021-04-25 10:11
Just to make it clear: French language is already added to Weblate and integrated with https://github.com/qiaeru/lang-french. Do you want to co-maintain French translations together with @qiaeru, so core and core extension will be exported to https://github.com/qiaeru/lang-french and community extensions to https://github.com/rooaaar/lang-french-extended? There is already similar setup for Turkish (separate extensions for core and community extensions), but they're maintained by the same person.

**Comment by qiaeru** [comment] 2021-04-25 10:25
The problem is that we don't translate everything the same way, but I didn't mind until now because we had two separate extensions. If Hiobi (or someone else) takes care of translating the third party extensions, the French translation that I manage will include these translations. So I will have to check and validate these translations, so that the translation is consistent as a whole.

I prefer to be the only one who can validate the translations for the moment.

**Comment by Hiobi** [comment] 2021-04-25 10:26
> core and core extension will be exported to https://github.com/qiaeru/lang-french and community extensions to https://github.com/rooaaar/lang-french-extended? 

Yes !
With @qiaeru (and others developpers) we had a [discuss about this two years ago](https://discuss.flarum.org/d/19971-extensions-translation-in-their-own-repository-or-in-language-pack/), we chosen to separate core and core extensions translations from community extensions translations. I think it's make sense to preserve it in Weblate.

**Comment by rob006** [comment] 2021-04-25 10:50
@qiaeru 

> So I will have to check and validate these translations, so that the translation is consistent as a whole.

I could configure bot to not export community extensions to your repository, so result will be the same as now (there will be two language packs: your language pack will contain only official extensions, Hiobi's language pack will contain only community extensions). You still would share the same language on Weblate, both with maintainer role, but you could just solve this by gentleman's agreement that you won't approve translations for community extensions, and @Hiobi won't approve translations for official extensions.

**Comment by Hiobi** [comment] 2021-04-25 10:55
> both with maintainer role, but you could just solve this by gentleman's agreement that you won't approve translations for community extensions, and @Hiobi won't approve translations for official extensions.

I totally agree ! I think it's the better way to proceed for the moment.
With @qiaeru we just had a discussion on Discord and we decided to exchange and harmonize our methods to translate into French, the weeks / months to come.

**Comment by rob006** [comment] 2021-04-25 10:55
> Do you talk about the yaml indentation and sort ?

YAML files are generated by bot, so order and indentation are forced by default YAML export settings, there is not much to discuss in this matter. :P With Weblate workflow YAML files are essentially machine-to-machine data format, these files are not intended to be read or edit by humans.

**Comment by Hiobi** [comment] 2021-04-25 10:59
> YAML files are generated by bot, so order and indentation are forced by default YAML export settings, there is not much to discuss in this matter. :P With Weblate workflow YAML files are essentially machine-to-machine data format, these files are not intended to be read or edit by humans.

Great ! I couldn't expect better. Like you say, *there is not much to discuss in this matter.* :D

**Comment by rob006** [comment] 2021-04-25 11:13
@qiaeru I need confirmation from you that you agree with this:

1. I configure bot to **not** export translations for community extensions to your language pack (https://github.com/qiaeru/lang-french) - only core and official translations will be exported to your language pack.
2. I configure bot to export **only** translations for community extensions to https://github.com/rooaaar/lang-french-extended.
3. I import existing translations from https://github.com/rooaaar/lang-french-extended to Weblate (it won't affect your language pack, since there are only translations for community extensions).
4. I grant maintainer role for French language on Weblate to @Hiobi.

In future we could just get rid of one language pack and export all translations to only one repository, since there are not many practical benefits from splitting translations to two language packs.

**Comment by qiaeru** [comment] 2021-04-25 13:01
> @qiaeru I need confirmation from you that you agree with this:
> 
> 1. I configure bot to **not** export translations for community extensions to your language pack (https://github.com/qiaeru/lang-french) - only core and official translations will be exported to your language pack.
> 2. I configure bot to export **only** translations for community extensions to https://github.com/rooaaar/lang-french-extended.
> 3. I import existing translations from https://github.com/rooaaar/lang-french-extended to Weblate (it won't affect your language pack, since there are only translations for community extensions).
> 4. I grant maintainer role for French language on Weblate to @Hiobi.
> 
> In future we could just get rid of one language pack and export all translations to only one repository, since there are not many practical benefits from splitting translations to two language packs.

This seems perfect. You're the best!

**Comment by rob006** [comment] 2021-04-26 19:56
I imported existing translations to Weblate and I configured exporting translations from Weblate to https://github.com/rooaaar/lang-french-extended - seems to be working fine.

Some extensions were not imported, since they're incompatible/outdated and they're not available in Weblate. You can easily find them on https://github.com/rooaaar/lang-french-extended/tree/master/locale - files not edited by bot in last commit are not supported by Weblate. You can leave them in your repository, but they're probably useless, since most of these extensions will not work on Flarum version required by your language pack.

Also two extensions had incorrect file names:

https://github.com/rooaaar/lang-french-extended/blob/master/locale/flarum-ext-guestengagement.yml
https://github.com/rooaaar/lang-french-extended/blob/master/locale/askvortsov-pipetables.yml

I imported them and they are already available in your language pack with correct file name - you can safely remove old files (they not worked anyway, since Flarum loads files only if they match extension ID).

**Comment by Hiobi** [comment] 2021-04-26 20:24
Great work Rob !
I check about useless files.
Thanks.

**Comment by rob006** [comment] 2021-05-01 16:05
I'm closing this issue, since it seems there is nothing more to do here. But if you have any questions, feel free to ask here or on [forum](https://discuss.flarum.org/d/20807-simplify-translation-process-with-weblate).

**Closed by rob006** 2021-05-01 16:05 UTC
Labels: language-pack
